# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test(self):
    # Test name: test
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://test.zone4code.com/")
    # 2 | setWindowSize | 697x728 | 
    self.driver.set_window_size(697, 728)
    # 3 | click | linkText=Titre | 
    self.driver.find_element(By.LINK_TEXT, "Titre").click()
    # 4 | click | css=#slick-slide15 .img-fluid | 
    self.driver.find_element(By.CSS_SELECTOR, "#slick-slide15 .img-fluid").click()
  
