USE [MyStore]
GO
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Afghanistan','AF','AFG');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Aland Islands','AX','ALA');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Albania','AL','ALB');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Algeria','DZ','DZA');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('American Samoa','AS','ASM');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Andorra','AD','AND');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Angola','AO','AGO');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Anguilla','AI','AIA');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Antarctica','AQ','ATA');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Antigua and Barbuda','AG','ATG');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Argentina','AR','ARG');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Armenia','AM','ARM');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Aruba','AW','ABW');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Australia','AU','AUS');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Austria','AT','AUT');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Azerbaijan','AZ','AZE');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Bahamas','BS','BHS');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Bahrain','BH','BHR');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Bangladesh','BD','BGD');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Barbados','BB','BRB');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Belarus','BY','BLR');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Belgium','BE','BEL');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Belize','BZ','BLZ');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Benin','BJ','BEN');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Bermuda','BM','BMU');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Bhutan','BT','BTN');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Bolivia','BO','BOL');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Bosnia and Herzegovina','BA','BIH');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Botswana','BW','BWA');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Bouvet Island','BV','BVT');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Brazil','BR','BRA');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('British Virgin Islands','VG','VGB');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('British Indian Ocean Territory','IO','IOT');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Brunei Darussalam','BN','BRN');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Bulgaria','BG','BGR');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Burkina Faso','BF','BFA');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Burundi','BI','BDI');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Cambodia','KH','KHM');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Cameroon','CM','CMR');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Canada','CA','CAN');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Cape Verde','CV','CPV');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Cayman Islands','KY','CYM');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Central African Republic','CF','CAF');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Chad','TD','TCD');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Chile','CL','CHL');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('China','CN','CHN');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Hong Kong, Special Administrative Region of China','HK','HKG');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Macao, Special Administrative Region of China','MO','MAC');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Christmas Island','CX','CXR');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Cocos (Keeling) Islands','CC','CCK');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Colombia','CO','COL');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Comoros','KM','COM');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Congo�(Brazzaville)','CG','COG');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Congo, Democratic Republic of the','CD','COD');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Cook Islands','CK','COK');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Costa Rica','CR','CRI');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('C�te d''Ivoire','CI','CIV');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Croatia','HR','HRV');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Cuba','CU','CUB');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Cyprus','CY','CYP');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Czech Republic','CZ','CZE');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Denmark','DK','DNK');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Djibouti','DJ','DJI');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Dominica','DM','DMA');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Dominican Republic','DO','DOM');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Ecuador','EC','ECU');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Egypt','EG','EGY');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('El Salvador','SV','SLV');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Equatorial Guinea','GQ','GNQ');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Eritrea','ER','ERI');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Estonia','EE','EST');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Ethiopia','ET','ETH');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Falkland Islands (Malvinas)','FK','FLK');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Faroe Islands','FO','FRO');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Fiji','FJ','FJI');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Finland','FI','FIN');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('France','FR','FRA');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('French Guiana','GF','GUF');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('French Polynesia','PF','PYF');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('French Southern Territories','TF','ATF');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Gabon','GA','GAB');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Gambia','GM','GMB');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Georgia','GE','GEO');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Germany','DE','DEU');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Ghana','GH','GHA');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Gibraltar','GI','GIB');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Greece','GR','GRC');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Greenland','GL','GRL');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Grenada','GD','GRD');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Guadeloupe','GP','GLP');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Guam','GU','GUM');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Guatemala','GT','GTM');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Guernsey','GG','GGY');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Guinea','GN','GIN');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Guinea-Bissau','GW','GNB');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Guyana','GY','GUY');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Haiti','HT','HTI');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Heard Island and Mcdonald Islands','HM','HMD');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Holy See�(Vatican City State)','VA','VAT');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Honduras','HN','HND');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Hungary','HU','HUN');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Iceland','IS','ISL');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('India','IN','IND');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Indonesia','ID','IDN');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Iran, Islamic Republic of','IR','IRN');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Iraq','IQ','IRQ');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Ireland','IE','IRL');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Isle of Man','IM','IMN');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Israel','IL','ISR');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Italy','IT','ITA');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Jamaica','JM','JAM');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Japan','JP','JPN');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Jersey','JE','JEY');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Jordan','JO','JOR');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Kazakhstan','KZ','KAZ');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Kenya','KE','KEN');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Kiribati','KI','KIR');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Korea, Democratic People''s Republic of','KP','PRK');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Korea, Republic of','KR','KOR');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Kuwait','KW','KWT');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Kyrgyzstan','KG','KGZ');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Lao PDR','LA','LAO');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Latvia','LV','LVA');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Lebanon','LB','LBN');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Lesotho','LS','LSO');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Liberia','LR','LBR');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Libya','LY','LBY');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Liechtenstein','LI','LIE');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Lithuania','LT','LTU');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Luxembourg','LU','LUX');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Macedonia, Republic of','MK','MKD');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Madagascar','MG','MDG');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Malawi','MW','MWI');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Malaysia','MY','MYS');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Maldives','MV','MDV');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Mali','ML','MLI');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Malta','MT','MLT');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Marshall Islands','MH','MHL');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Martinique','MQ','MTQ');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Mauritania','MR','MRT');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Mauritius','MU','MUS');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Mayotte','YT','MYT');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Mexico','MX','MEX');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Micronesia, Federated States of','FM','FSM');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Moldova','MD','MDA');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Monaco','MC','MCO');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Mongolia','MN','MNG');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Montenegro','ME','MNE');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Montserrat','MS','MSR');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Morocco','MA','MAR');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Mozambique','MZ','MOZ');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Myanmar','MM','MMR');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Namibia','NA','NAM');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Nauru','NR','NRU');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Nepal','NP','NPL');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Netherlands','NL','NLD');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Netherlands Antilles','AN','ANT');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('New Caledonia','NC','NCL');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('New Zealand','NZ','NZL');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Nicaragua','NI','NIC');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Niger','NE','NER');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Nigeria','NG','NGA');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Niue','NU','NIU');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Norfolk Island','NF','NFK');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Northern Mariana Islands','MP','MNP');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Norway','NO','NOR');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Oman','OM','OMN');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Pakistan','PK','PAK');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Palau','PW','PLW');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Palestinian Territory, Occupied','PS','PSE');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Panama','PA','PAN');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Papua New Guinea','PG','PNG');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Paraguay','PY','PRY');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Peru','PE','PER');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Philippines','PH','PHL');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Pitcairn','PN','PCN');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Poland','PL','POL');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Portugal','PT','PRT');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Puerto Rico','PR','PRI');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Qatar','QA','QAT');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('R�union','RE','REU');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Romania','RO','ROU');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Russian Federation','RU','RUS');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Rwanda','RW','RWA');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Saint-Barth�lemy','BL','BLM');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Saint Helena','SH','SHN');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Saint Kitts and Nevis','KN','KNA');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Saint Lucia','LC','LCA');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Saint-Martin (French part)','MF','MAF');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Saint Pierre and Miquelon','PM','SPM');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Saint Vincent and Grenadines','VC','VCT');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Samoa','WS','WSM');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('San Marino','SM','SMR');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Sao Tome and Principe','ST','STP');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Saudi Arabia','SA','SAU');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Senegal','SN','SEN');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Serbia','RS','SRB');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Seychelles','SC','SYC');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Sierra Leone','SL','SLE');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Singapore','SG','SGP');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Slovakia','SK','SVK');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Slovenia','SI','SVN');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Solomon Islands','SB','SLB');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Somalia','SO','SOM');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('South Africa','ZA','ZAF');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('South Georgia and the South Sandwich Islands','GS','SGS');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('South Sudan','SS','SSD');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Spain','ES','ESP');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Sri Lanka','LK','LKA');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Sudan','SD','SDN');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Suriname�*','SR','SUR');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Svalbard and Jan Mayen Islands','SJ','SJM');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Swaziland','SZ','SWZ');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Sweden','SE','SWE');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Switzerland','CH','CHE');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Syrian Arab Republic�(Syria)','SY','SYR');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Taiwan, Republic of China','TW','TWN');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Tajikistan','TJ','TJK');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Tanzania�*, United Republic of','TZ','TZA');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Thailand','TH','THA');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Timor-Leste','TL','TLS');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Togo','TG','TGO');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Tokelau','TK','TKL');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Tonga','TO','TON');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Trinidad and Tobago','TT','TTO');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Tunisia','TN','TUN');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Turkey','TR','TUR');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Turkmenistan','TM','TKM');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Turks and Caicos Islands','TC','TCA');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Tuvalu','TV','TUV');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Uganda','UG','UGA');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Ukraine','UA','UKR');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('United Arab Emirates','AE','ARE');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('United Kingdom','GB','GBR');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('United States of America','US','USA');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('United States Minor Outlying Islands','UM','UMI');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Uruguay','UY','URY');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Uzbekistan','UZ','UZB');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Vanuatu','VU','VUT');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Venezuela�(Bolivarian Republic of)','VE','VEN');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Viet Nam','VN','VNM');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Virgin Islands, US','VI','VIR');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Wallis and Futuna Islands','WF','WLF');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Western Sahara','EH','ESH');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Yemen','YE','YEM');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Zambia','ZM','ZMB');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Zimbabwe','ZW','ZWE');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Unknown','XX','XXX');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('Kosovo','XK','UNK');
INSERT INTO Countries(Name,CodeAlpha2,CodeAlpha3) VALUES ('International','ww','INT');
